### ISSUE TITLE
剪映和达芬奇没有作用

### ISSUE THREAD

**Issue by actforjason** [RichardLuo0/qtct-for-windows#1]
Windows的剪映和达芬奇 UI字体都不太好，调节无效怎么办？

**Comment by RichardLuo0** [comment]
目标软件必须跟qtct用同一个编译环境（msvc或者mingw，我只提供了msvc版本），然后软连接platformthemes到软件根目录底下，设置环境变量 QT_QPA_PLATFORMTHEME=qtct。
有些软件可能自己改了qt，也不一定会去用。
